version: '3'

networks:
  geomiq-network:

volumes:
  dbdata:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../api:/var/www/api
      - ../frontend:/var/www/frontend
    ports:
      - '3000:3000'
      - '4000:4000'
    networks:
      - geomiq-network

  api:
    build:
      context: ./
      dockerfile: php/Dockerfile
    image: php-with-laravel-dependencies
    container_name: api
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ../api:/var/www/api
    networks:
      - geomiq-network

  frontend:
    image: node:lts-alpine
    tty: true
    container_name: frontend
    working_dir: /var/www/frontend
    volumes:
      - ../frontend:/var/www/frontend
    networks:
      - geomiq-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - geomiq-network

  testing-db:
    image: mysql:5.7
    container_name: testing-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - geomiq-network

  swagger:
    image: swaggerapi/swagger-ui:v3.24.3
    container_name: swagger
    volumes:
      - ../apidocs/geomiq_quotes.v1.yaml:/docs/swagger_file.json
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      - SWAGGER_JSON=/docs/swagger_file.json

